version: "3.8"
services:
  mysqldb:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_DATABASE: 'mysqldb'
      MYSQL_ROOT_PASSWORD: 'root'
    ports:
      - "3306:3306"
    expose:
      - 3306
    networks:
      - banksystem-mysql-network

  configserver:
    image: banksystem/configserver
    mem_reservation: 700m
    ports:
      - "8070:8070"
    networks:
      - banksystem-mysql-network

  eurekaserver:
    image: banksystem/eurekaserver
    mem_reservation: 700m
    ports:
      - "8090:8090"
    networks:
      - banksystem-mysql-network
    environment:
      SPRING_CONFIG_IMPORT: optional:configserver:http://configserver:8070/
    depends_on:
      - configserver
    deploy:
      restart_policy:
        condition: on-failure
        delay: 30s
        max_attempts: 3
        window: 120s

  account_instance_1:
    image: banksystem/account:latest
    mem_reservation: 700m
    ports:
      - "8081:8081"
    networks:
      - banksystem-mysql-network
    environment:
      SPRING_PROFILES_ACTIVE : "default"
      SPRING_CONFIG_IMPORT: optional:configserver:http://configserver:8070/
      #EUREKA_CLIENT_SERVICEURL_DEFAULTZONE : http://localhost:8090/
    depends_on:
      - mysqldb
      - configserver
      - eurekaserver
    deploy:
      restart_policy:
        condition: on-failure
        delay: 45s
        max_attempts: 3
        window: 120s
  account_instance_2:
    image: banksystem/account:latest
    mem_reservation: 700m
    ports:
      - "8082:8081"
    networks:
      - banksystem-mysql-network
    environment:
      SPRING_PROFILES_ACTIVE: "default"
      SPRING_CONFIG_IMPORT: optional:configserver:http://configserver:8070/
      #EUREKA_CLIENT_SERVICEURL_DEFAULTZONE : http://localhost:8090/
    depends_on:
      - mysqldb
      - configserver
      - eurekaserver
    deploy:
      restart_policy:
        condition: on-failure
        delay: 45s
        max_attempts: 3
        window: 120s

  loans_instance_1:
    image: banksystem/loans:latest
    mem_reservation: 700m
    ports:
      - "7000:7000"
    networks:
      - banksystem-mysql-network
    environment:
      SPRING_PROFILES_ACTIVE : "default"
      SPRING_CONFIG_IMPORT: optional:configserver:http://configserver:8070/
      #EUREKA_CLIENT_SERVICEURL_DEFAULTZONE : http://localhost:8090/
    depends_on:
      - mysqldb
      - configserver
      - eurekaserver
    deploy:
      restart_policy:
        condition: on-failure
        delay: 35s
        max_attempts: 3
        window: 120s
  loans_instance_2:
    image: banksystem/loans:latest
    mem_reservation: 700m
    ports:
      - "7001:7000"
    networks:
      - banksystem-mysql-network
    environment:
      SPRING_PROFILES_ACTIVE: "default"
      SPRING_CONFIG_IMPORT: optional:configserver:http://configserver:8070/
      # EUREKA_CLIENT_SERVICEURL_DEFAULTZONE : http://localhost:8090/
    depends_on:
      - mysqldb
      - configserver
      - eurekaserver
    deploy:
      restart_policy:
        condition: on-failure
        delay: 45s
        max_attempts: 3
        window: 120s
  cardsinstance_1:
    image: banksystem/cards:latest
    mem_reservation: 700m
    ports:
      - "9000:9000"
    networks:
      - banksystem-mysql-network
    environment:
      SPRING_PROFILES_ACTIVE : "default"
      SPRING_CONFIG_IMPORT: optional:configserver:http://configserver:8070/
      # EUREKA_CLIENT_SERVICEURL_DEFAULTZONE : http://localhost:8090/
    depends_on:
      - mysqldb
      - configserver
      - eurekaserver
    deploy:
      restart_policy:
        condition: on-failure
        delay: 45s
        max_attempts: 3
        window: 120s
  cardsinstance_2:
    image: banksystem/cards:latest
    mem_reservation: 700m
    ports:
      - "9001:9000"
    networks:
      - banksystem-mysql-network
    environment:
      SPRING_PROFILES_ACTIVE: "default"
      SPRING_CONFIG_IMPORT: optional:configserver:http://configserver:8070/
      # EUREKA_CLIENT_SERVICEURL_DEFAULTZONE : http://localhost:8090/
    depends_on:
      - mysqldb
      - configserver
      - eurekaserver
    deploy:
      restart_policy:
        condition: on-failure
        delay: 45s
        max_attempts: 3
        window: 120s
  gatewayserver:
    image: banksystem/gatewayserver
    mem_reservation: 700m
    ports:
      - "8091:8091"
    networks:
      - banksystem-mysql-network
    environment:
      SPRING_CONFIG_IMPORT: optional:configserver:http://configserver:8070/
      # EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://localhost:8090/
    depends_on:
      - configserver
      - eurekaserver
      - account_instance_1
      - account_instance_2
      - loans_instance_1
      - loans_instance_2
      - cardsinstance_1
      - cardsinstance_2
    deploy:
      restart_policy:
        condition: on-failure
        delay: 50s
        max_attempts: 3
        window: 180s
networks:
  banksystem-mysql-network: