# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

deploymentName: loans-deployment
deploymentLabel: loans

replicaCount: 2

image:
  repository: ansoumana/loans
  tag: latest

containerPort: 7000

service:
  type: ClusterIP
  port: 7000
  targetPort: 7000

config_enabled: true
zipkin_enabled: true
profile_enabled: true
eureka_enabled: true
keycloak_enabled: false
resouceserver_enabled: false